"""
JMeter Performance Utility — Streamlit app.

Two workflows:
  1. JTL -> HTML report (upload .jtl, generate a self-contained HTML report, download).
  2. Compare HTML reports (upload two HTML reports, generate a comparison report,
     download). Works with reports made by this tool and with external
     JMeter Aggregate / single-file plugin HTML reports.
"""

import streamlit as st

from src.jtl_parser import load_many, compute_statistics
from src.report_generator import generate_html_report
from src.html_comparator import extract_stats_from_html, compare
from src.comparison_report import generate_comparison_html

st.set_page_config(page_title="JMeter Performance Utility", page_icon="📊", layout="wide")

# Session memory for chaining generate -> compare.
st.session_state.setdefault("generated", [])  # list of (name, html)

st.title("📊 JMeter Performance Utility")
st.caption("Convert JTL results into HTML reports and compare two reports for regressions.")

tab_gen, tab_cmp = st.tabs(["① JTL → HTML Report", "② Compare HTML Reports"])


# ---------------------------------------------------------------------------
# Tab 1: JTL -> HTML report
# ---------------------------------------------------------------------------
with tab_gen:
    st.subheader("Generate an HTML report from JTL")
    st.write(
        "Upload one or more JMeter `.jtl` result files (CSV format). "
        "Multiple files are merged — useful for distributed/multi-engine runs."
    )

    jtl_files = st.file_uploader(
        "Upload .jtl file(s)", type=["jtl", "csv", "xml"],
        accept_multiple_files=True, key="jtl_upload",
    )
    report_title = st.text_input("Report title", value="JMeter Performance Report")

    if st.button("Generate HTML Report", type="primary", disabled=not jtl_files):
        try:
            with st.spinner("Parsing JTL and building report…"):
                payload = [(f.name, f.getvalue()) for f in jtl_files]
                df = load_many(payload)
                stats = compute_statistics(df, report_title.strip() or "JMeter Performance Report")
                html = generate_html_report(stats)

            ov = stats["overall"]
            c1, c2, c3, c4, c5 = st.columns(5)
            c1.metric("Samples", f"{stats['meta']['total_samples']:,}")
            c2.metric("Avg (ms)", f"{ov['average']:,.0f}")
            c3.metric("90th pct (ms)", f"{ov['pct90']:,.0f}")
            c4.metric("Error %", f"{ov['error_pct']:.2f}%")
            c5.metric("Throughput /s", f"{ov['throughput']:,.2f}")

            fname = (report_title.strip() or "report").replace(" ", "_") + ".html"
            st.download_button(
                "⬇️ Download HTML Report", data=html, file_name=fname,
                mime="text/html", type="primary",
            )

            # Keep it for the compare tab.
            st.session_state["generated"] = (
                [(fname, html)] + st.session_state["generated"]
            )[:5]

            with st.expander("Preview report", expanded=True):
                st.components.v1.html(html, height=620, scrolling=True)

            st.info("This report is now also available to select in the **Compare** tab.")
        except Exception as exc:  # noqa: BLE001
            st.error(f"Could not generate report: {exc}")


# ---------------------------------------------------------------------------
# Tab 2: Compare two HTML reports
# ---------------------------------------------------------------------------
with tab_cmp:
    st.subheader("Compare two HTML reports")
    st.write(
        "Provide two HTML reports — **A = baseline**, **B = current**. "
        "Accepts reports generated by this tool, JMeter *Aggregate Report* exports, "
        "or single-file plugin HTML reports containing a statistics table."
    )

    generated_names = [n for n, _ in st.session_state["generated"]]
    gen_lookup = dict(st.session_state["generated"])

    def _slot(letter: str):
        """Return (name, bytes) for one comparison slot, or None."""
        st.markdown(f"**Report {letter}**")
        source = "Upload file"
        if generated_names:
            source = st.radio(
                f"Source for {letter}", ["Upload file", "Use a generated report"],
                key=f"src_{letter}", horizontal=True,
            )
        if source == "Use a generated report" and generated_names:
            pick = st.selectbox(
                f"Generated report for {letter}", generated_names, key=f"pick_{letter}",
            )
            return pick, gen_lookup[pick].encode("utf-8")
        up = st.file_uploader(
            f"Upload HTML report {letter}", type=["html", "htm"], key=f"html_{letter}",
        )
        return (up.name, up.getvalue()) if up else None

    col_a, col_b = st.columns(2)
    with col_a:
        slot_a = _slot("A")
    with col_b:
        slot_b = _slot("B")

    ready = slot_a is not None and slot_b is not None
    if st.button("Compare Reports", type="primary", disabled=not ready):
        try:
            with st.spinner("Extracting statistics and comparing…"):
                stats_a = extract_stats_from_html(slot_a[1])
                stats_b = extract_stats_from_html(slot_b[1])
                cmp = compare(stats_a, stats_b, slot_a[0], slot_b[0])
                html = generate_comparison_html(cmp)

            # Headline deltas on overall.
            cols = st.columns(4)
            wanted = {"Average": 0, "90% Line": 1, "Error %": 2, "Throughput": 3}
            for m in cmp["overall"]:
                if m["metric"] in wanted:
                    c = cols[wanted[m["metric"]]]
                    delta_color = "inverse" if m["metric"] != "Throughput" else "normal"
                    c.metric(m["metric"], f"{m['b']:,.2f}", f"{m['pct']:+.1f}%",
                             delta_color=delta_color)

            st.download_button(
                "⬇️ Download Comparison Report", data=html,
                file_name="comparison_report.html", mime="text/html", type="primary",
            )
            with st.expander("Preview comparison", expanded=True):
                st.components.v1.html(html, height=620, scrolling=True)
        except Exception as exc:  # noqa: BLE001
            st.error(f"Could not compare reports: {exc}")

st.divider()
st.caption(
    "For response time and error metrics lower is better; for throughput higher is better. "
    "Changes ≥10% are flagged as improvement/regression."
)
