"""Render a side-by-side comparison HTML report from a comparison dict."""

import datetime as _dt

from .report_generator import _CSS

_EXTRA_CSS = """
.legend{display:flex;gap:18px;margin:8px 0 22px;font-size:12px;color:var(--muted)}
.dot{display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:6px;vertical-align:middle}
.dot.good{background:var(--good)}.dot.bad{background:var(--bad)}.dot.neutral{background:var(--muted)}
.up{color:var(--bad)}.down{color:var(--good)}
.good-txt{color:var(--good)}.bad-txt{color:var(--bad)}.neutral-txt{color:var(--muted)}
.names{display:flex;gap:14px;margin:6px 0 18px;flex-wrap:wrap}
.names .n{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:8px 14px;font-size:13px}
.names .n b{color:var(--accent)}
.tag{font-size:10px;padding:2px 7px;border-radius:20px;border:1px solid var(--line);color:var(--muted)}
.tag.added{color:var(--good);border-color:var(--good)}
.tag.removed{color:var(--bad);border-color:var(--bad)}
section{margin:26px 0}
section h2{font-size:15px;font-weight:620;border-left:3px solid var(--accent);padding-left:10px}
"""


def _fmt(v, unit):
    if unit == "%":
        return f"{v:,.2f}%"
    if unit == "":
        return f"{v:,.0f}"
    return f"{v:,.0f}"


def _pct_cell(pct, status):
    if status == "good":
        arrow = "&#9660;" if pct < 0 else "&#9650;"
        return f'<td class="good-txt">{arrow} {pct:+.1f}%</td>'
    if status == "bad":
        arrow = "&#9650;" if pct > 0 else "&#9660;"
        return f'<td class="bad-txt">{arrow} {pct:+.1f}%</td>'
    return f'<td class="neutral-txt">{pct:+.1f}%</td>'


def _metric_table(block):
    rows = []
    for m in block:
        rows.append(
            f"<tr><td>{m['metric']}</td>"
            f"<td>{_fmt(m['a'], m['unit'])}</td>"
            f"<td>{_fmt(m['b'], m['unit'])}</td>"
            f"<td>{m['diff']:+,.2f}</td>"
            f"{_pct_cell(m['pct'], m['status'])}</tr>"
        )
    return (
        "<table><thead><tr><th>Metric</th><th>Baseline (A)</th>"
        "<th>Current (B)</th><th>&Delta;</th><th>&Delta;%</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table>"
    )


def _txn_section(transactions):
    blocks = []
    for t in transactions:
        tag = ""
        if t["presence"] == "added":
            tag = ' <span class="tag added">new in B</span>'
        elif t["presence"] == "removed":
            tag = ' <span class="tag removed">only in A</span>'
        blocks.append(
            f'<div class="panel" style="margin-bottom:16px">'
            f'<h3 style="color:var(--txt);font-size:14px">{t["label"]}{tag}</h3>'
            f'{_metric_table(t["metrics"])}</div>'
        )
    return "".join(blocks)


def generate_comparison_html(cmp: dict) -> str:
    generated = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Performance Comparison Report</title>
<style>{_CSS}{_EXTRA_CSS}</style></head>
<body><div class="wrap">
<header><h1>Performance Comparison Report</h1>
<div class="sub">Generated {generated} &middot; Baseline (A) vs Current (B)</div></header>

<div class="names">
  <div class="n"><b>A &middot; Baseline</b> &nbsp;{cmp['name_a']}</div>
  <div class="n"><b>B &middot; Current</b> &nbsp;{cmp['name_b']}</div>
</div>
<div class="legend">
  <span><span class="dot good"></span>Improvement (&ge;{int(10)}%)</span>
  <span><span class="dot bad"></span>Regression (&ge;{int(10)}%)</span>
  <span><span class="dot neutral"></span>Within threshold</span>
</div>

<section><h2>Overall</h2><div class="panel">{_metric_table(cmp['overall'])}</div></section>
<section><h2>By Transaction</h2>{_txn_section(cmp['transactions'])}</section>

<footer>Generated by JMeter Performance Utility &middot; A=baseline, B=current. For response time &amp; errors, lower is better; for throughput, higher is better.</footer>
</div></body></html>"""
